name = "Server Utilities"
author = "badooga"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cb240ea25a31522a7ea18218343dc5df32085420d8ce31a536e4a4695a3284e7"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.3"
