name = "Quilt Server Utilities"
author = "badooga"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "031a0b694588599ca6b73ce4e529b825abc3cd1e954e1d63a1ddbc9e2886ede8"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.3"
