name = "Quilt Server Utilities"
author = "badooga"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5f337cbde10b1957a2eff913d4a93b36b9883aef9a7caab7df6df56e424a5c44"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.3"
