name = "Server Utilities"
author = "badooga"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "152dfb861bbba1c08f23866a80e9a8c5bfb4d88ca3665230844d5f1c3afc8465"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.3"
