name = "Server Utilities"
author = "badooga"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "377d1093acfccfa06da92954e30b7b7a20ed6600c1a3fedd7cdffd4eafde9de1"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.3"
